/*
 * ------------------------------------------------------------------------------
 * Project: symon
 * Version: 0.0.1
 * Description: Tiny Command Line Interface Remote System Monitor.
 * Author: lzcdr
 * Date: 2024-03-04 10:07:41
 * ------------------------------------------------------------------------------
 * This file was automatically generated by the Bytesnap RPC (version 0.1.0) 
 * project generator.
 * ------------------------------------------------------------------------------
 */

// request.hpp

#ifndef __REQUEST_HPP
#define __REQUEST_HPP
 
#include "bytesnap.hpp"



namespace symon {

struct Request
{
    uint32_t signature = 3735928559;

    Request() {}

    template <typename T = bytesnap::writer> static size_t encode(const Request& source, T& writer) {
        size_t before = writer.size();

        writer.write_uint32_t(source.signature);

        size_t after = writer.size();
        return after - before;
    }

    template <typename T = bytesnap::reader> static bool decode(Request& target, T& reader) {
        std::optional<uint32_t> signature = reader.read_uint32_t();
        if (!signature) return false;
        target.signature = signature.value();

        return true;
    }

};

} // namespace symon

#endif // __REQUEST_HPP