/*
 * ------------------------------------------------------------------------------
 * Project: symon
 * Version: 0.0.1
 * Description: Tiny Command Line Interface Remote System Monitor.
 * Author: lzcdr
 * Date: 2024-03-04 10:07:41
 * ------------------------------------------------------------------------------
 * This file was automatically generated by the Bytesnap RPC (version 0.1.0) 
 * project generator.
 * ------------------------------------------------------------------------------
 */
#ifndef __SYMON_MESSAGE_ID_HPP
#define __SYMON_MESSAGE_ID_HPP

#include <cstdint>

namespace symon {

enum class symon_method_id : uint32_t
{
    QUERY = 0

};

} // namespace symon

#endif //__SYMON_MESSAGE_ID_HPP