/*
 * ------------------------------------------------------------------------------
 * Project: symon
 * Version: 0.0.1
 * Description: Tiny Command Line Interface Remote System Monitor.
 * Author: lzcdr
 * Date: 2024-03-04 10:07:41
 * ------------------------------------------------------------------------------
 * This file was automatically generated by the Bytesnap RPC (version 0.1.0) 
 * project generator.
 * ------------------------------------------------------------------------------
 */

#include <cassert>
#include <iostream>

#include "symon_client.hpp"

int main(int argc, char** argv)
{
    if (argc != 3) {
        std::cout << "Usage: provide two arguments - ip-address (127.0.0.1) and port" << std::endl;
        return 1;
    }
    std::string address = argv[1];
    std::string port = argv[2];

    symon::symon_client client(address, port);
    
    {
        symon::Request request;
        symon::Response reply;

        if (client.symon_query_request(request, reply) == true) {
            std::cout << "cpu utilization:  " << reply.cpu_utilisation << "%" << std::endl;
            std::cout << "total ram:        " << reply.total_ram << std::endl;
            std::cout << "free ram:         " << reply.free_ram << std::endl;
            std::cout << "total disk space: " << reply.total_disk_space << std::endl;
            std::cout << "free disk space:  " << reply.free_disk_space << std::endl;
        } else {
            std::cout << "error occured." << std::endl;
        }
    }

    return 0;
}
