/*
 * ------------------------------------------------------------------------------
 * Project: symon
 * Version: 0.0.1
 * Description: Tiny Command Line Interface Remote System Monitor.
 * Author: lzcdr
 * Date: 2024-03-04 10:07:41
 * ------------------------------------------------------------------------------
 * This file was automatically generated by the Bytesnap RPC (version 0.1.0) 
 * project generator.
 * ------------------------------------------------------------------------------
 */
#include "vst_message.hpp"

#include "request.hpp"
#include "response.hpp"

namespace symon {

struct symon_query_message_processor
{
    vst::message_error_code operator()(const vst::buffer& input, vst::buffer& output);

private:
    void get_system_metrics(Response& response);
    double get_cpu_load();
};

} // namespace symon